services:
  deluge:
    image: lscr.io/linuxserver/deluge:amd64-libtorrentv1-version-2.1.1
    container_name: deluge
    # user: 0:0 # should be owner of volumes
    environment:
      - TZ=Europe/Paris
      - DELUGE_LOGLEVEL=error #optional
      - UMASK_SET=000 #optional
    volumes:
      - /mnt/Partage/Logiciels/deluge/config:/config:rw
      - /mnt/Partage/Logiciels/deluge/DelugeDL:/downloads:rw
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
